name: Pipeline

on:
  pull_request:
  push:
    branches: [main]

jobs:
  verify:
    uses: JJT-INGSIS/github-workflows/.github/workflows/kotlin-service-pipeline.yml@v1
    secrets:
      GH_PACKAGES_USER: ${{ secrets.GH_PACKAGES_USER }}
      GH_PACKAGES_READ_TOKEN: ${{ secrets.GH_PACKAGES_READ_TOKEN }}
